export type ARModel = {
  src: string;
  scale?: number;
};

/**
 * Maps product subcategories to open-source GLB models
 * (aedifex models, MIT licensed) for the "View in Your Room" AR feature.
 * Products without a matching subcategory (e.g. sofa) show no AR button.
 */
export const AR_MODELS: Record<string, ARModel> = {
  // Chairs
  'executive-chair': { src: '/assets/models/office-chair.glb' },
  'manager-chair': { src: '/assets/models/office-chair.glb' },
  'staff-chair': { src: '/assets/models/office-chair.glb' },
  'visitor-chair': { src: '/assets/models/office-chair.glb' },
  'gaming-chair': { src: '/assets/models/office-chair.glb' },
  'dining-chair': { src: '/assets/models/dining-chair.glb' },
  'bar-stool': { src: '/assets/models/dining-chair.glb', scale: 0.8 },
  // Tables
  'executive-table': { src: '/assets/models/office-table.glb' },
  'manager-table': { src: '/assets/models/office-table.glb' },
  'staff-table': { src: '/assets/models/office-table.glb' },
  'height-adjustable-table': { src: '/assets/models/office-table.glb' },
  'center-table': { src: '/assets/models/coffee-table.glb' },
};

/**
 * Composed meeting-room demo scene (table + 4 chairs) generated by
 * scripts/compose-meeting-room.mjs.
 */
export const MEETING_ROOM: ARModel = {
  src: '/assets/models/beso-meeting-room.glb',
};

export function getProductModel(subcategory: string): ARModel | null {
  return AR_MODELS[subcategory] ?? null;
}

/**
 * URL template for the bespoke per-product GLB (detailed Hunyuan/SF3D shape
 * models generated from the client's product photos). Whether the file
 * actually exists is resolved server-side (page checks fs before wiring).
 */
export function productModelUrl(slug: string): string {
  return `/assets/models/products/${slug}.glb`;
}

/**
 * Resolve the best available AR/3D model for a product: prefer the detailed
 * per-product GLB when a slug is provided, else fall back to the shared
 * subcategory placeholder. Existence is checked by the caller when possible.
 */
export function resolveProductModel(
  slug: string | undefined,
  subcategory: string | undefined,
): ARModel | null {
  if (slug) return { src: productModelUrl(slug) };
  return subcategory ? getProductModel(subcategory) : null;
}